### ISSUE TITLE
一直弹出“输入验证码”

### ISSUE THREAD

**Issue by jwjawa** [yltx/vscode-luogu#10]
~~直角~~
我确信我的密码和验证码输入正确，但是会一直弹出“输入验证码”，我尝试过按Esc但是无果，禁用后未重启vsc再启用仍然会弹出（指没有登录操作的情况下），只有重启vsc才可以停止，但如果登录的话还是会出现问题。
另外，我都快退役了，我4月份提的issue还是没有等到（悲

**Comment by jwjawa** [comment]
哦，禁用了之后如果没重启还是一直弹非要重启

**Comment by yltx** [comment]
已知bug，是luogu更新API所致，正在研究出错原因及解决方法，请临时使用cookieslogin登录，以解决弹窗问题。

**Comment by jwjawa** [comment]
好的谢谢qwq

**Comment by jwjawa** [comment]
发现cookies登录没用，输入用户名或者id以后没有反应

**Comment by yltx** [comment]
fixed
