### ISSUE TITLE
登录账号显示“会话超时，请刷新页面后重试”

### ISSUE THREAD

**Issue by 1379Post** [yltx/vscode-luogu#15]
![image](https://user-images.githubusercontent.com/54499417/127960529-1f58dfd4-ab69-48ca-ba37-d9e3642a5e52.png)

**Comment by yltx** [comment]
是已知bug。原因是使用的登录借口不稳定。由于找不到根本原因（为什么不稳定），所以没办法修。解决方式有二：1.使用cookies login2.等一段时间重试。
