### ISSUE TITLE
关于登录的小问题

### ISSUE THREAD

**Issue by Adentent** [yltx/vscode-luogu#19]
当尝试登陆洛谷时，验证码需要输入两次，并且在第二次输入时即使正确，也会在右下角弹出提示“您已经登录”；
当洛谷登录完毕后，
![image](https://user-images.githubusercontent.com/96329894/160404108-2357ede5-1709-4d5e-b84f-bb72d441a60c.png)
依然会显示未登录。

**Comment by yltx** [comment]
已经了解的bug，测试结果为你谷返回了一个403 forbidden的结果，具体原因不明。
登录功能一直出各种各样原因不明的问题，可能要等你谷正式开放api之后才能完整修复。
现阶段请使用cookies login功能代替。
