### ISSUE TITLE
能否将Ctrl+Shift+P的搜索功能改变成英文/拼音输入？

### ISSUE THREAD

**Issue by Adentent** [yltx/vscode-luogu#20]
rt，现在的中文输入搜索过于繁琐，能否将拼音/英文作为其“描述”？
就像下面的一样↓
![image](https://user-images.githubusercontent.com/96329894/160613707-0c7e2a45-0b83-441a-82bb-e0b03a196647.png)

**Comment by yltx** [comment]
下版本会更新的。

**Comment by yltx** [comment]
经研究，此命令不是由vscode-luogu实现的，而是直接来源于vscode。所以如果您觉得使用麻烦，建议为其添加快捷键，我们没法修改他的描述。

**Comment by Adentent** [comment]
emm...您是不是会错意了...
![image](https://user-images.githubusercontent.com/96329894/161055070-26b92781-21db-4728-98d4-d14f9762798b.png)
意思是说“**就像**下面一样”，譬如说将“查看题目”这一项增加一个描述“View Problems”

**Comment by Adentent** [comment]
这样子的话在搜索时就可以不用将输入法切换到中文再输入“查看题目”了，即可直接用英文输入法输入”view problems“。

**Comment by yltx** [comment]
草  这个意思啊  那咕了
（因为我没有找到实现方式，我所见过的所有扩展都没有提供有效的方式，我又完全不想去再翻一遍扩展开发说明）

**Comment by Adentent** [comment]
> 草 这个意思啊 那咕了 （因为我没有找到实现方式，我所见过的所有扩展都没有提供有效的方式，我又完全不想去再翻一遍扩展开发说明）

![image](https://user-images.githubusercontent.com/96329894/161269337-54fa0751-f49e-49fb-8af3-18760117d42d.png)
为您提供样本:)

**Comment by yltx** [comment]
> > 草 这个意思啊 那咕了 （因为我没有找到实现方式，我所见过的所有扩展都没有提供有效的方式，我又完全不想去再翻一遍扩展开发说明）
> 
> ![image](https://user-images.githubusercontent.com/96329894/161269337-54fa0751-f49e-49fb-8af3-18760117d42d.png) 为您提供样本:)

没用  因为我在这些插件的package.json中都没发现有效内容。

**Comment by Adentent** [comment]
就是说，有没有可能是多种语言

**Comment by yltx** [comment]
> 就是说，有没有可能是多种语言

可能可以，但是我并不知道怎么实现，而且也没有空实现。

**Comment by Adentent** [comment]
（或者直接在后面打个括号写英文）
![image](https://user-images.githubusercontent.com/96329894/161271373-cdff2538-19b2-46fd-8835-78025b26dce0.png)

**Comment by yltx** [comment]
这或许可以。

**Comment by yltx** [comment]
> 这或许可以。

添加了  但是要下版本更新才能看到。
由于下版本是大更新（新增题单相关功能），所以可能要等一段时间
~（换句话说就是最近游戏有活动没空搞插件）~
