### ISSUE TITLE
请问适配新版 AT 题号的功能写好了吗？

### ISSUE THREAD

**Issue by purple-vine** [yltx/vscode-luogu#28]
在 vscode 中看题很舒服，但是现在更改了 AT 题号规则，导致 AT 题库无法在 vscode 中查看，望能适配新题号规则

**Comment by yltx** [comment]
> 在 vscode 中看题很舒服，但是现在更改了 AT 题号规则，导致 AT 题库无法在 vscode 中查看，望能适配新题号规则

在咕。事实上，本项目最早会咕到明年6月，因为几名主要开发者都在忙文化课。
