### ISSUE TITLE
犇犇是不是寄了

### ISSUE THREAD

**Issue by Qwdb** [yltx/vscode-luogu#33]
![QQ截图20231017163446](https://github.com/yltx/vscode-luogu/assets/62271743/6ef82677-9f05-4d39-83ae-964eb2d05ea5)
![QQ截图20231017164428](https://github.com/yltx/vscode-luogu/assets/62271743/76bbf068-9d86-40a3-8691-dda92a433485)

**Comment by Qwdb** [comment]
看不到犇犇
另外这个发射犇犇也没有用，发不出去

**Comment by yltx** [comment]
> 看不到犇犇 另外这个发射犇犇也没有用，发不出去
早就寄了，目前有更重要的开发计划，暂时不准备修复
