### ISSUE TITLE
[feat] 团队题单功能

### ISSUE THREAD

**Issue by wpcwzy** [yltx/vscode-luogu#45]

**Comment by wpcwzy** [comment]
reference: https://github.com/0f-0b/luogu-api-docs/blob/main/teams.md

**Comment by Mr-Python-in-China** [comment]
![image](https://github.com/yltx/vscode-luogu-developer/assets/89737170/3da5ad7c-b04d-4a97-a570-6fe7307ffbc3)
没问题啊
可以看

**Comment by wpcwzy** [comment]
我刚刚从在master分支上测试，团队私有提单看不了，比如69742这个

**Comment by Mr-Python-in-China** [comment]
> 我刚刚从在master分支上测试，团队私有提单看不了，比如69742这个

（我本来就没有看这个题单的权限 给我我也打不开）

**Comment by wpcwzy** [comment]
我的锅，现在确实能打开了（

**Comment by Mr-Python-in-China** [comment]
无法复现，使用 `Close as not planned`
