### ISSUE TITLE
[用户体验] 提交按钮操作复杂

### ISSUE THREAD

**Issue by wpcwzy** [yltx/vscode-luogu#46]
![image](https://user-images.githubusercontent.com/16263217/230753064-5c1f9ae3-ddf7-47d4-9920-516a356ee43f.png)

**Comment by yltx** [comment]
这个有改进思路吗

**Comment by wpcwzy** [comment]
刚提这个issue时候的解决思路是：在提交前用vscode api将焦点切换回上一个活跃窗口。但简单搜了搜貌似没搜到这样的api

现在的想法是充分利用侧边栏，把功能性的按钮（交题、评测记录什么的）放在侧边栏，webview只用来渲染文字、题干，不提供交互功能。这样也和大部分vscode插件的操作逻辑相符。

同时，如果按后一种思路来改进的话，或许更符合微软官方对vscode插件使用webview视图的建议
![image](https://github.com/yltx/vscode-luogu-developer/assets/16263217/3ab04ce2-7042-4ac1-b7c1-e1c68645ac7a)

**Comment by Mr-Python-in-China** [comment]
能不能用个变量记录上一个活动的窗口

侧边栏的话一次开多个题不好做？

**Comment by gi-b716** [comment]
> 能不能用个变量记录上一个活动的窗口
> 
> 侧边栏的话一次开多个题不好做？

做一下展开列表？
每个列表项后面加个提交按钮
