### ISSUE TITLE
[feat]关于全网动态

### ISSUE THREAD

**Issue by Rickyxrc** [yltx/vscode-luogu#51]
请问永久关闭全网动态是技术问题还是社区管理员的要求？

如果是技术问题的话 `https://www.luogu.com.cn/api/feed/list` 在不带 cookie 的情况下 `GET / POST` 都可以获取全网动态，且没有 api 鉴权。

另外，我这边关于犇犇的所有功能均无法正常使用，回去我试着修一下。

**Comment by wpcwzy** [comment]
根据相关规定，不适合在插件中出现社区社交性质的板块

**Comment by wpcwzy** [comment]
根据相关规定，不适合在插件中出现社区社交性质的板块

**Comment by Rickyxrc** [comment]
> 根据相关规定，不适合在插件中出现社区社交性质的板块

那这一部分的内容是直接删除还是保持原样不动呢？
