### ISSUE TITLE
突然不能使用了

### ISSUE THREAD

**Issue by xyf007** [yltx/vscode-luogu#6]
显示`command 'luogu.signin' not found`

**Comment by jiyu596** [comment]
老版本还能用（吧）

**Comment by yltx** [comment]
开发者一点问题都没有，麻烦提供截图

**Comment by jiyu596** [comment]
> 开发者一点问题都没有，麻烦提供截图

![2020-09-02 (1)](https://user-images.githubusercontent.com/43328428/91991491-8827a200-ed65-11ea-9b15-ae3722970df7.png)

**Comment by yltx** [comment]
> > 开发者一点问题都没有，麻烦提供截图
> 
> ![2020-09-02 (1)](https://user-images.githubusercontent.com/43328428/91991491-8827a200-ed65-11ea-9b15-ae3722970df7.png)

此问题已发现。但是是在部分用户上发现的，开发者无法复现，故目前未确定问题原因。估计得等一段时间才能解决，可尝试倒回至4.4.9版本使用。

**Comment by gandyli** [comment]
已于 v4.5.1 中修复
