### ISSUE TITLE
扩展与 WSL （Win10 下的 Linux 子系统）一起用的时候失效

### ISSUE THREAD

**Issue by jiyu596** [yltx/vscode-luogu#7]
这个洛谷的扩展应该是作用于本地的，然而其 `"remote.extensionKind"` 的设置似乎为 `"workspace"`。这会导致在与 WSL 和别的一些远程开发的方式一起用的时候失效。我把
```
//in settings.json
    "remote.extensionKind": {
        "yltx.vscode-luogu": "ui"
    }
```
这样强制设置为 `"ui"` 就可以用了，请求把这个扩展的属性设置好！

**Comment by yltx** [comment]
> 这个洛谷的扩展应该是作用于本地的，然而其 `"remote.extensionKind"` 的设置似乎为 `"workspace"`。这会导致在与 WSL 和别的一些远程开发的方式一起用的时候失效。我把
> 
> ```
> //in settings.json
>     "remote.extensionKind": {
>         "yltx.vscode-luogu": "ui"
>     }
> ```
> 
> 这样强制设置为 `"ui"` 就可以用了，请求把这个扩展的属性设置好！

了解了，等下就改

**Comment by ljcbaby** [comment]
![image](https://user-images.githubusercontent.com/46277145/124433358-3ac0fa80-dda5-11eb-8c7c-12032164481b.png)
在与Remote-SSH同时使用时也是失效的

**Comment by yltx** [comment]
> ![image](https://user-images.githubusercontent.com/46277145/124433358-3ac0fa80-dda5-11eb-8c7c-12032164481b.png)
> 在与Remote-SSH同时使用时也是失效的

这个跟WSL没关系。是4.5.4的通病（并不知道为什么，是个玄学错误。）预计将在4.5.5中通过回退代码修复。

**Comment by ljcbaby** [comment]
> > ![image](https://user-images.githubusercontent.com/46277145/124433358-3ac0fa80-dda5-11eb-8c7c-12032164481b.png)
> > 在与Remote-SSH同时使用时也是失效的
> 
> 这个跟WSL没关系。是4.5.4的通病（并不知道为什么，是个玄学错误。）预计将在4.5.5中通过回退代码修复。

现在能操作了，但提示会话超时

**Comment by yltx** [comment]
> > > ![image](https://user-images.githubusercontent.com/46277145/124433358-3ac0fa80-dda5-11eb-8c7c-12032164481b.png)
> > > 在与Remote-SSH同时使用时也是失效的
> > 
> > 
> > 这个跟WSL没关系。是4.5.4的通病（并不知道为什么，是个玄学错误。）预计将在4.5.5中通过回退代码修复。
> 
> 现在能操作了，但提示会话超时

等一会就好了 这是测试的时候就存在的玄学问题 无法修复。

**Comment by ljcbaby** [comment]
> > > > ![image](https://user-images.githubusercontent.com/46277145/124433358-3ac0fa80-dda5-11eb-8c7c-12032164481b.png)
> > > > 在与Remote-SSH同时使用时也是失效的
> > > 
> > > 
> > > 这个跟WSL没关系。是4.5.4的通病（并不知道为什么，是个玄学错误。）预计将在4.5.5中通过回退代码修复。
> > 
> > 
> > 现在能操作了，但提示会话超时
> 
> 等一会就好了 这是测试的时候就存在的玄学问题 无法修复。

我的应该不是玄学问题，而是有两步验证。

**Comment by yltx** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/46277145/124433358-3ac0fa80-dda5-11eb-8c7c-12032164481b.png)
> > > > > 在与Remote-SSH同时使用时也是失效的
> > > > 
> > > > 
> > > > 这个跟WSL没关系。是4.5.4的通病（并不知道为什么，是个玄学错误。）预计将在4.5.5中通过回退代码修复。
> > > 
> > > 
> > > 现在能操作了，但提示会话超时
> > 
> > 
> > 等一会就好了 这是测试的时候就存在的玄学问题 无法修复。
> 
> 我的应该不是玄学问题，而是有两步验证。

首先，不两步验证也会出现这个问题，所以我无法断定您的问题是不是两步验证引起的；其次，由于所有开发者均没有两步验证的账号，所以两步验证功能无法测试，即没有条件复现您所说的问题。

**Comment by ljcbaby** [comment]
我是开了洛谷的两部验证的，应该是这个问题。
而且不是自己想就可以设置两部验证的吗？

**Comment by yltx** [comment]
> 我是开了洛谷的两部验证的，应该是这个问题。
> 而且不是自己想就可以设置两部验证的吗？

不是 您没明白我的意思 您两步验证出了这个问题，而这个问题在没有两步验证的账号上同样有出现，所以我认为他不是两步验证的特异性问题；其次，开发者们基本摸不到手机，开两步验证干什么？

**Comment by ljcbaby** [comment]
我明白，但我是100%复现，而不是过一会重试就行，所以我的应该是两步验证导致的问题。
至于为什么要开两步验证，不想设置复杂密码，两步验证当动态密码更安全

**Comment by yltx** [comment]
> 我明白，但我是100%复现，而不是过一会重试就行，所以我的应该是两步验证导致的问题。
> 至于为什么要开两步验证，不想设置复杂密码，两步验证当动态密码更安全

您能复现，但我没有条件复现啊，您要我如何去修一个我无法复现的bug？
我为您提供两种解决方案：1. 将您的账号临时提供给开发组，开发组抽空进行测试与bug修复；2. 您使用cookieslogin功能代替，等若干个版本后我们用更heavy的方法重构login功能（很可能不会，因为vscode-luogu开发的时候就希望是轻量级的解决方案。）
