### ISSUE TITLE
时间错误

### ISSUE THREAD

**Issue by gi-b716** [yltx/vscode-luogu#76]
在 犇犇-我关注的 中出现了时间错误。

- vscode-luogu显示：2024-05-03 **07**:32:18
- 实际时间：2024-05-03 **23**:32:18

疑似错误的代码：
https://github.com/yltx/vscode-luogu-developer/blob/57ce600ae733d3162f8f925bb415115e1708cfd4/src/commands/benben/index.ts#L58-L64

**Comment by wpcwzy** [comment]
v4.9.0发布后已修复，详见[72843cf](https://github.com/yltx/vscode-luogu-developer/commit/72843cf5e9bedb11228b711857e405ac1e909995)
