### ISSUE TITLE
[问题] 题目链接错误

### ISSUE THREAD

**Issue by dunxuan** [yltx/vscode-luogu#77]
会出现undefined后缀
示例：
[NOIP2015 提高组] 跳石头 | [P2678](https://www.luogu.com.cn/problem/P2678undefined)
![image](https://github.com/yltx/vscode-luogu-developer/assets/33661049/1ade5845-8187-4989-a29d-dea1c412fa96)

**Comment by wpcwzy** [comment]
https://github.com/yltx/vscode-luogu-developer/blob/57ce600ae733d3162f8f925bb415115e1708cfd4/src/model/Problem.ts#L147-L148

感觉是第148行的问题

**Comment by wpcwzy** [comment]
[c09119c ](https://github.com/yltx/vscode-luogu-developer/commit/c09119cc3a8b24a31b62986fd79b29169e6a8fd2)已经修复了，还没发新版本，等明天更新一下插件试试
