### ISSUE TITLE
P开头的题号跳转链接有问题

### ISSUE THREAD

**Issue by andywowws** [yltx/vscode-luogu#78]
如P3384点击蓝色字体跳转https://www.luogu.com.cn/problem/P3384undefined  
实际应该跳转https://www.luogu.com.cn/problem/P3384
![image](https://github.com/yltx/vscode-luogu-developer/assets/87009024/168e720c-f055-45a7-bab8-e21b418f05f8)

**Comment by wpcwzy** [comment]
v4.9.0发布后已修复
