### ISSUE TITLE
更改跳转域名为 luogu.com.cn

### ISSUE THREAD

**Issue by yzy-1** [yltx/vscode-luogu#8]
RT

比如在查看一道题目 (如 P1001) 时, 会在右边题目预览的大标题中显示一个指向 `https://www.luogu.org/problem/P1001` 的蓝色文本链接, 但是 luogu 官方推荐的域名是 `luogu.com.cn`, 请求更给为更加规范的域名 (如 `https://www.luogu.com.cn/problem/P1001`.

**Comment by yltx** [comment]
知道了，等会修

**Comment by yltx** [comment]
fixed.
