### ISSUE TITLE
侧边栏使用“最近浏览”功能

### ISSUE THREAD

**Issue by Mr-Python-in-China** [yltx/vscode-luogu#81]
目前计划：
- 在侧边栏添加“历史记录”功能，记录最近打开的题目、题单、比赛；
- 将题目提交的方式迁移到历史记录里，在该题目项目的右侧添加一个按钮用于提交；

现在担心操作会不会有些繁琐 要是没大有反对意见我就去做了

**Comment by Mr-Python-in-China** [comment]
Fix https://github.com/yltx/vscode-luogu-developer/issues/46

**Comment by bijhla** [comment]
建议不将题目提交的方式迁移，而是同时保留两种提交方式，即既可以用快捷键在现在打开的题目页面交，也能在历史记录中交

**Comment by Mr-Python-in-China** [comment]
> 建议不将题目提交的方式迁移，而是同时保留两种提交方式，即既可以用快捷键在现在打开的题目页面交，也能在历史记录中交

注意到大量加群的群友的第一句话是提问提交题目为什么不生效，值得怀疑该操作是否太过反人类，还有无保留的必要？

**Comment by bijhla** [comment]
> > 建议不将题目提交的方式迁移，而是同时保留两种提交方式，即既可以用快捷键在现在打开的题目页面交，也能在历史记录中交
> 
> 注意到大量加群的群友的第一句话是提问提交题目为什么不生效，值得怀疑该操作是否太过反人类，还有无保留的必要？

主要是感觉用快捷键交题的话会很顺手（刚刚写完题或调完的时候）

**Comment by Mr-Python-in-China** [comment]
> > > 建议不将题目提交的方式迁移，而是同时保留两种提交方式，即既可以用快捷键在现在打开的题目页面交，也能在历史记录中交
> > 
> > 
> > 注意到大量加群的群友的第一句话是提问提交题目为什么不生效，值得怀疑该操作是否太过反人类，还有无保留的必要？
> 
> 主要是感觉用快捷键交题的话会很顺手（刚刚写完题或调完的时候）

哦你说快捷键 我还以为是题目页的那个按钮

这个会留着

**Comment by Mr-Python-in-China** [comment]
看来没啥意见 那我开始做了
