### ISSUE TITLE
添加 "自动提交" 选项

### ISSUE THREAD

**Issue by Natural-selection1** [yltx/vscode-luogu#87]
# 4.10.0是史诗级更新
:tada::tada::tada:

如题, 感觉目前除了"传送至CPH"是需要自己选择语言外, 感觉其他所有的都可以直接"自动提交"了(相较于目前的"自动选中"和"自动填充")

特别是在启用luogu.guessProblemID 和 配置 luogu.defaultLanguageVersion 后感觉"自动提交"是不是更好一点?

**Comment by Mr-Python-in-China** [comment]
添加三个设置
- 打开题目时直接选中自动猜测的文件名
- 提交题目时直接选中自动猜测的文件名
- 提交题目时直接选中默认语言

这样合适吗

**Comment by Natural-selection1** [comment]
~~话说4.10.1更新说明中的"打开题目时也自动猜测pid"是啥时候会触发?作用是?~~
浅浅说一下我的设想
1. 设置项Guess Problem ID 从“尝试通过CPH配置或文件名猜测PID并自动填充”修改为“……自动提交”
2. 添加设置项“提交题目时依赖文件后缀名自动提交对应语言类型”
3. 添加设置性“提交题目时依赖Default Language version自动提交相应语言的语言版本”

这样正好对应现在提交题目时需要按下的三次回车，直接一条龙了

不知道大佬怎么看？

**Comment by Mr-Python-in-China** [comment]
语言类型感觉没啥必要 这个应该不会错 选中自动提交的话直接跳过去就可以吧

**Comment by Mr-Python-in-China** [comment]
> ~话说4.10.1更新说明中的"打开题目时也自动猜测pid"是啥时候会触发?作用是?~

你如果打开了一个已经创建好的文件 这个时候打开题目可以猜

**Comment by Natural-selection1** [comment]
主要目的就是为了提交代码后不再需要按回车去选些什么，具体细节倒是没什么所谓了

**Comment by Mr-Python-in-China** [comment]
> 添加三个设置
> 
> * 打开题目时直接选中自动猜测的文件名
> * 提交题目时直接选中自动猜测的文件名
> * 提交题目时直接选中默认语言

那我就这么干了
