### ISSUE TITLE
添加配置项“"发送至cph"时创建的文件添加题目名”

### ISSUE THREAD

**Issue by Natural-selection1** [yltx/vscode-luogu#88]
本人小菜鸡一枚，最近开始刷洛谷题单，一些体验上感觉可以优化的地方就直接说出来了，如有打扰还请多多担待

感觉现在“发送至cph”后，所创建文件的文件名感觉很不直观（不是很方便复习、回看），不知道可不可以增加如题设置项，直接读取题目名称接在现在的文件名后面

> 现在
> Luogu_P_1420
> Luogu_P_1002
> Luogu_CF_1_A

> 修改后
> Luogu_P_1420_最长连号
> Luogu_P_1002_[NOIP2002 普及组] 过河卒
> Luogu_CF_1_A_Theatre Square
> (或者加个 :Theatre Square  or "Theatre Square" 方便定位?)

不知道实现上会不会有困难

**Comment by wpcwzy** [comment]
感谢反馈！

感觉这个功能建议挺合理的，会考虑实现。
