### ISSUE TITLE
vscode-luogu插件支持开启-O2优化提交代码吗

### ISSUE THREAD

**Issue by RectalGod** [yltx/vscode-luogu#92]
诶呀作者, 不好意思, issue不小心提交到另一个仓库了...

![图片](https://github.com/user-attachments/assets/fda9669b-e951-46af-b1d9-49837a3fbdac)

> [!TIP]
> 因为我使用插件提交的代码并没有显示-O2标签, 我想问一下, vscode-luogu插件支持开启-O2优化提交代码吗, 在wiki内我没有找到有关说明

**Comment by wpcwzy** [comment]
目前在提交语言为C++时，会弹出选择C++版本的选择框，可以选择是否启用O2优化。但是对于Rust，目前确实没有开启O2的选项，会在近期修复，感谢反馈！

**Comment by Mr-Python-in-China** [comment]
rust都支持O2了

惊恐
