### ISSUE TITLE
洛谷增加了图形验证码, 目前无法使用插件提交代码

### ISSUE THREAD

**Issue by RectalGod** [yltx/vscode-luogu#97]
![截图 2024-11-21 20-20-35](https://github.com/user-attachments/assets/a700b14a-324f-4cbc-91eb-0e3792b05554)

**Comment by Sving1024** [comment]
和 #96 一个问题。

**Comment by relunctance** [comment]
同一个问题 
![Uploading s6.png…]()

**Comment by relunctance** [comment]
同一个问题

**Comment by relunctance** [comment]
![Uploading s6.png…](同一个问题 )

**Comment by relunctance** [comment]
![Uploading s6.png…]()

**Comment by relunctance** [comment]
![同一个问题](https://raw.githubusercontent.com/relunctance/2/refs/heads/master/s6.png?token=GHSAT0AAAAAAC2HDZ6WN7G3IY5B4FQXZERGZ2QFOVQ)

**Comment by Mr-Python-in-China** [comment]
duplicate #96
